# Generated by Django 4.2.16 on 2024-12-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_Cuentas', '0003_alter_cliente_nombres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
